### ISSUE TITLE
Dim not work

### ISSUE THREAD

**Issue by wenLiangcan** [LukasKalbertodt/term-painter#12]
The statements:

``` rust
println!("{}", Style::default().dimmed().paint("test 1"));  // rust-ansi-term
println!("{}", Dim.paint("test 2"));  // term-painter
```

generated the following outputs:

![](http://dimg.vim-cn.com/7f/f1f065186496406083ebcffe6b360e58adbc72.png)

**Comment by LukasKalbertodt** [comment]
Ok, I'm investigating right now. What terminal are you using? Looks a bit like Ubuntu Default, which I'm using too.

When using `term` directly, it doesn't work either:

``` rust
t.attr(term::Attr::Dim);    // Ok(false)
(write!(t, "foo")).unwrap();
assert!(t.reset().unwrap());
```

This outputs the same `foo^[(B^[[0m` as in your picture. `Ok(false)` means that the attribute isn't supported on the current terminal. But apparently my terminal does support dim/faint mode, since printing `println!("\x1b[2mtest 1\x1b[0m");` has the desired output.

Right now I think it's a bug in `term`. Will investigate further.

**Comment by wenLiangcan** [comment]
I'm using Terminator on Arch Linux.

My terminal does support dim/faint mode too and the picture is the outputs saved in a file.

**Comment by LukasKalbertodt** [comment]
Seems to be resolved now (was a bug in ncurses). The second line in your example results in `^[[2mtest 2^[(B^[[0m` now.
